"""Corpus v3: registry licence parsing, source adapters on tiny local fixture
archives (no network), and an end-to-end --root build with dedup against v2,
decontamination, store layout and manifests."""

import gzip
import hashlib
import importlib.util
import io
import json
import shutil
import tarfile
import zipfile
from array import array
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
spec = importlib.util.spec_from_file_location("build_corpus_v3", ROOT / "data" / "build_corpus_v3.py")
v3 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(v3)
reg, v2 = v3.reg, v3.v2
HAVE_FORGE = v2.FORGE.exists() and v2.TOKENIZER.exists()

CONTAMINATED = ("assert fixture_contaminated_function(alpha, beta, gamma, delta, epsilon, zeta, eta, theta, iota, kappa) "
                "== lambda_value")
JAVA = """package org.example.lib;

/** Small immutable pair used by the fixture library. */
public final class Pair<A, B> {
    private final A first;
    private final B second;

    public Pair(A first, B second) {
        this.first = first;
        this.second = second;
    }

    public A first() { return first; }

    public B second() { return second; }
}
"""
JAVA_CONTAMINATED = f"""package org.example.lib;

final class Leak {{
    // {CONTAMINATED}
    static int leak() {{ return 1; }}
}}
"""
RUBY = """module Fixgem
  # Formats a greeting for the given name, falling back to "world".
  def self.greet(name = nil)
    who = name.to_s.strip
    who = "world" if who.empty?
    "Hello, #{who}!"
  end
end
"""
RUBY_DUPLICATE = """# This file is byte-identical to a document of corpus v2.
def duplicated_in_v2(x)
  x * 2 + 1
end
"""
GENERATED_JAVA = """// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fixture.proto
package org.example.lib;

public final class FixtureProto {
  private FixtureProto() {}
}
"""
HASKELL = """module Data.Fixture (chunksOf) where

-- | Split a list into chunks of the given size.
chunksOf :: Int -> [a] -> [[a]]
chunksOf _ [] = []
chunksOf n xs = take n xs : chunksOf n (drop n xs)
"""
PROSE = ("This package provides a small, well documented library for the fixture tests. It explains how to install it, "
         "how to call the main functions, and which guarantees the implementation gives about ordering, laziness and "
         "error handling. Every example in this document is meant to be read by people, not machines.\n")


def tgz(files: dict[str, str | bytes]) -> bytes:
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz") as tf:
        for name, data in files.items():
            raw = data.encode() if isinstance(data, str) else data
            info = tarfile.TarInfo(name)
            info.size = len(raw)
            tf.addfile(info, io.BytesIO(raw))
    return buf.getvalue()


def zipb(files: dict[str, str]) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        for name, data in files.items():
            zf.writestr(name, data)
    return buf.getvalue()


def gem(files: dict[str, str]) -> bytes:
    buf = io.BytesIO()
    parts = {"metadata.gz": gzip.compress(b"--- !ruby/object:Gem::Specification\n"), "data.tar.gz": tgz(files)}
    with tarfile.open(fileobj=buf, mode="w") as tf:
        for name, raw in parts.items():
            info = tarfile.TarInfo(name)
            info.size = len(raw)
            tf.addfile(info, io.BytesIO(raw))
    return buf.getvalue()


def pom(lics: list[str], parent: tuple | None = None, doctype: bool = False) -> bytes:
    lic = "".join(f"<license><name>{x}</name></license>" for x in lics)
    par = f"<parent><groupId>{parent[0]}</groupId><artifactId>{parent[1]}</artifactId><version>{parent[2]}</version></parent>" if parent else ""
    head = '<!DOCTYPE x [<!ENTITY a "aaaa">]>' if doctype else ""
    return (f'<?xml version="1.0"?>{head}<project xmlns="http://maven.apache.org/POM/4.0.0">{par}<name>Fixture</name>'
            f"<url>https://example.org/lib</url><licenses>{lic}</licenses><developers><developer><name>Ada</name></developer>"
            "</developers></project>").encode()


def metadata(release: str, versions: list[str]) -> bytes:
    vs = "".join(f"<version>{v}</version>" for v in versions)
    return f"<metadata><versioning><release>{release}</release><versions>{vs}</versions></versioning></metadata>".encode()


class FakeNet:
    """URL -> bytes; records every request."""

    def __init__(self, routes: dict[str, bytes]):
        self.routes, self.calls = routes, []

    def __call__(self, url, timeout=90, accept=None, max_bytes=reg.MAX_DOWNLOAD):  # noqa: ANN001
        self.calls.append(url)
        return self.routes.get(url)


M = "https://repo1.maven.org/maven2/org/example"
HK = "https://hackage.haskell.org/package"


def routes() -> dict[str, bytes]:
    gem_bytes = gem({"lib/fixgem.rb": RUBY, "lib/fixgem/dup.rb": RUBY_DUPLICATE, "README.md": PROSE + "Ruby edition.",
                     "History.rdoc": PROSE + "1.0"})
    cabal = "name: fixpkg\nversion: 0.10.1\nLicense:             BSD3\nlicense-file: LICENSE\nauthor: Grace\nhomepage: https://example.org/fixpkg\n"
    return {
        f"{M}/lib/maven-metadata.xml": metadata("1.2.0-M1", ["1.0.0", "1.1.0", "1.2.0-M1"]),
        f"{M}/lib/1.1.0/lib-1.1.0.pom": pom([], parent=("org.example", "parent", "7")),
        f"{M}/parent/7/parent-7.pom": pom(["The Apache Software License, Version 2.0"]),
        f"{M}/lib/1.1.0/lib-1.1.0-sources.jar": zipb({"org/example/lib/Pair.java": JAVA, "org/example/lib/Leak.java": JAVA_CONTAMINATED,
                                                      "org/example/lib/FixtureProto.java": GENERATED_JAVA,
                                                      "org/example/lib/package.html": f"<html><body><p>{PROSE}</p><script>x()</script></body></html>",
                                                      "META-INF/MANIFEST.MF": "Manifest-Version: 1.0\n"}),
        f"{M}/gpl-lib/maven-metadata.xml": metadata("2.0", ["2.0"]),
        f"{M}/gpl-lib/2.0/gpl-lib-2.0.pom": pom(["Eclipse Public License - v 2.0"]),
        "https://rubygems.org/api/v1/gems/fixgem.json": json.dumps({
            "name": "fixgem", "version": "1.0.0", "licenses": ["MIT"], "authors": "Ruby Fixture", "homepage_uri": "https://example.org/fixgem",
            "gem_uri": "https://rubygems.org/gems/fixgem-1.0.0.gem", "sha": hashlib.sha256(gem_bytes).hexdigest()}).encode(),
        "https://rubygems.org/gems/fixgem-1.0.0.gem": gem_bytes,
        f"{HK}/fixpkg/preferred": json.dumps({"normal-version": ["0.9", "0.10.1", "0.2.0"], "deprecated-version": ["0.11"]}).encode(),
        f"{HK}/fixpkg-0.10.1/fixpkg-0.10.1.tar.gz": tgz({"fixpkg-0.10.1/fixpkg.cabal": cabal, "fixpkg-0.10.1/src/Data/Fixture.hs": HASKELL,
                                                        "fixpkg-0.10.1/README.md": PROSE + "Haskell edition.", "fixpkg-0.10.1/LICENSE": "BSD"}),
    }


# ---------------------------------------------------------------- licences and parsing


def test_licence_policy_allows_permissive_and_rejects_copyleft_and_unknown():
    for ok in ["MIT", "Apache-2.0", "BSD-3-Clause", "MIT OR Apache-2.0", "The Apache Software License, Version 2.0", "ISC", "CC0-1.0",
               "Public Domain", "0BSD"]:
        assert reg.licence_ok(ok), ok
    for bad in [None, "", "GPL-3.0", "GNU General Public License v3 (GPLv3)", "LGPLv2.1", "MIT OR GPLv3", "AGPL3",
                "Apache-2.0 OR GNU Lesser General Public License", "Eclipse Public License - v 2.0", "EPL-2.0 OR Apache-2.0",
                "MPL-2.0", "Ruby", "AllRightsReserved", "Bouncy Castle Licence", "CDDL + GPLv2 with classpath exception",
                "CC-BY-SA-4.0", "MIT OR CC-BY-SA-4.0"]:
        assert not reg.licence_ok(bad), bad


def test_cabal_licence_fields_and_legacy_names():
    assert reg.cabal_licence("name: x\nLicense:   BSD3\nlicense-file: LICENSE\n") == "BSD-3-Clause"
    assert reg.cabal_licence("license-file: LICENSE\nlicense: PublicDomain\n") == "Public Domain"
    assert reg.cabal_licence("cabal-version: 3.0\nlicense: MIT OR Apache-2.0\n") == "MIT OR Apache-2.0"
    assert reg.cabal_licence("name: x\nlicense-file: LICENSE\n") is None
    assert reg.licence_ok(reg.cabal_licence("License: BSD3\n"))
    for bad in ("GPL-3", "LGPL-2.1", "OtherLicense", "AllRightsReserved", "MPL-2.0"):
        assert not reg.licence_ok(reg.cabal_licence(f"license: {bad}\n")), bad
    assert reg.cabal_fields("name: x\nlibrary\n  build-depends: base\n  license: GPL-3\n") == {"name": "x"}  # top-level fields only


def test_pom_licences_follow_parent_and_refuse_dtds(monkeypatch):
    net = FakeNet(routes())
    monkeypatch.setattr(reg, "fetch", net)
    lic, info = reg.maven_licence("org.example", "lib", "1.1.0")
    assert lic == "The Apache Software License, Version 2.0" and info["parent"] == ("org.example", "parent", "7")
    assert info["authors"] == "Ada" and info["url"] == "https://example.org/lib"
    assert reg.pom_info(pom(["MIT", "Apache-2.0"]))["licenses"] == ["MIT", "Apache-2.0"]
    assert reg.pom_info(pom(["MIT"], doctype=True)) is None


def test_maven_version_skips_prereleases():
    assert reg.maven_version(metadata("1.2.0-M1", ["1.0.0", "1.1.0", "1.2.0-M1"])) == "1.1.0"
    assert reg.maven_version(metadata("33.3.1-jre", ["33.3.0-jre", "33.3.1-jre"])) == "33.3.1-jre"
    assert reg.maven_version(metadata("2.0.0-RC2", ["2.0.0-alpha1", "2.0.0-beta3", "2.0.0-RC2"])) is None


def test_file_selection_and_javadoc_text():
    code = ["org/x/Foo.java", "src/x.kt", "lib/x.rb", "lib/tasks/x.rake", "src/Data/X.hs", "Setup.lhs", "a/b.py", "a/b.go", "a/b.scala"]
    general = ["README.md", "doc/usage.rdoc", "docs/guide.rst", "docs/intro.adoc", "org/x/package.html", "overview.html"]
    none = ["META-INF/MANIFEST.MF", "META-INF/maven/x/pom.xml", "CHANGELOG.md", "History.rdoc", "NEWS.md", "LICENSE.txt",
            "node_modules/a.js", "x.min.js", "tests/fixtures.md", "org/x/Other.html", "x.c"]
    assert [reg.kind_of(p) for p in code] == ["code"] * len(code)
    assert [reg.kind_of(p) for p in general] == ["general"] * len(general)
    assert [reg.kind_of(p) for p in none] == [None] * len(none)
    text = reg.html_text("<html><head><style>p{}</style></head><body><h1>Title</h1><p>One &amp; two.</p><script>bad()</script>"
                         "<ul><li>a</li><li>b</li></ul></body></html>")
    assert text == "Title\n\nOne & two.\n\na\n\nb"


# ---------------------------------------------------------------- source adapters (offline)


def test_maven_source_reads_sources_jar_with_provenance(monkeypatch):
    net = FakeNet(routes())
    monkeypatch.setattr(reg, "fetch", net)
    entry, files = reg.maven("org.example:lib")
    jar = routes()[f"{M}/lib/1.1.0/lib-1.1.0-sources.jar"]
    assert entry["version"] == "1.1.0" and entry["license"].startswith("The Apache") and "parent" in entry["license_from"]
    assert entry["sha256"] == hashlib.sha256(jar).hexdigest() and entry["url"].endswith("lib-1.1.0-sources.jar")
    assert "lib 1.1.0 by Ada" in entry["attribution"] and "status" not in entry
    kinds = {p: k for p, k, _ in files}
    assert kinds == {"org/example/lib/Pair.java": "code", "org/example/lib/Leak.java": "code", "org/example/lib/FixtureProto.java": "code",
                     "org/example/lib/package.html": "general"}
    html = next(t for p, _, t in files if p.endswith("package.html"))
    assert "<p>" not in html and "x()" not in html and "fixture tests" in html


def test_maven_rejects_non_allowlisted_licence_without_downloading(monkeypatch):
    net = FakeNet(routes())
    monkeypatch.setattr(reg, "fetch", net)
    entry, files = reg.maven("org.example:gpl-lib")
    assert entry["status"] == "rejected-licence" and files == [] and entry["license"].startswith("Eclipse")
    assert not any(u.endswith("-sources.jar") for u in net.calls)


def test_rubygems_source_licence_checksum_and_files(monkeypatch):
    r = routes()
    net = FakeNet(r)
    monkeypatch.setattr(reg, "fetch", net)
    entry, files = reg.rubygems("fixgem")
    assert entry["license"] == "MIT" and entry["version"] == "1.0.0" and entry["authors"] == "Ruby Fixture"
    assert {p: k for p, k, _ in files} == {"lib/fixgem.rb": "code", "lib/fixgem/dup.rb": "code", "README.md": "general"}
    for lics, status in ((["GPL-2.0"], "rejected-licence"), (["Ruby"], "rejected-licence"), ([], "rejected-licence"), (["MIT"], "checksum-mismatch")):
        meta = json.loads(r["https://rubygems.org/api/v1/gems/fixgem.json"]) | {"licenses": lics}
        if status == "checksum-mismatch":
            meta["sha"] = "0" * 64
        net.routes["https://rubygems.org/api/v1/gems/fixgem.json"] = json.dumps(meta).encode()
        entry, files = reg.rubygems("fixgem")
        assert entry["status"] == status and files == [], lics


def test_hackage_source_picks_newest_version_and_reads_cabal_licence(monkeypatch):
    r = routes()
    net = FakeNet(r)
    monkeypatch.setattr(reg, "fetch", net)
    entry, files = reg.hackage("fixpkg")
    assert entry["version"] == "0.10.1" and entry["license"] == "BSD-3-Clause" and entry["license_from"] == ".cabal license field"
    assert entry["authors"] == "Grace" and entry["homepage"] == "https://example.org/fixpkg"
    assert {p: k for p, k, _ in files} == {"fixpkg-0.10.1/src/Data/Fixture.hs": "code", "fixpkg-0.10.1/README.md": "general"}
    tar = f"{HK}/fixpkg-0.10.1/fixpkg-0.10.1.tar.gz"
    net.routes[tar] = tgz({"fixpkg-0.10.1/fixpkg.cabal": "name: fixpkg\nlicense: GPL-3\n", "fixpkg-0.10.1/src/A.hs": HASKELL})
    entry, files = reg.hackage("fixpkg")
    assert entry["status"] == "rejected-licence" and entry["license"] == "GPL-3" and files == []


def test_plan_interleaves_registries_and_skips_v2(monkeypatch):
    seen = {}

    def lister(r):
        def f(n, skip):
            seen[r] = skip
            return [x for x in [f"{r}1", f"{r}2", f"{r}3"] if x not in skip][:n]
        return f

    monkeypatch.setattr(reg, "LISTS", {r: lister(r) for r in v3.REGISTRIES})
    a = v3.argparse.Namespace(packages=None, registries=["maven", "pypi"], limit=2)
    tasks = v3.plan(a, {"pypi:pypi1", "npm:x"})
    assert tasks == [("maven", "maven1"), ("pypi", "pypi2"), ("maven", "maven2"), ("pypi", "pypi3")]
    assert seen == {"maven": set(), "pypi": {"pypi1"}}


def test_fetch_refuses_non_https_urls_from_metadata():
    assert reg.fetch("file:///etc/passwd") is None and reg.fetch("http://example.org/x.gem") is None and reg.fetch("") is None


def test_generated_code_markers():
    for header in ("// Code generated by protoc-gen-go. DO NOT EDIT.", "// This file is @generated by prost-build.",
                   "// Bindings generated by `windows-bindgen` 0.62.1", "# Auto-generated file, do not modify", GENERATED_JAVA):
        assert v3.GENERATED.search(header), header
    for text in (JAVA, RUBY, HASKELL, 'def generate(x):\n    """Return a generated id."""\n'):
        assert not v3.GENERATED.search(text), text


def test_repair_and_fast_hashes(tmp_path):
    p = tmp_path / "d.jsonl"
    rows = [{"h": "a" * 40, "k": "code", "s": "x:y", "p": "p", "t": "t"}, {"h": "b" * 40, "t": "u"}]
    p.write_text("".join(json.dumps(r) + "\n" for r in rows) + '{"h": "cccc')
    v3.repair(p)
    assert p.read_text().endswith("\n") and list(v3.doc_hashes(p)) == ["a" * 40, "b" * 40]
    v3.repair(p)
    assert len(p.read_text().splitlines()) == 2


# ---------------------------------------------------------------- end-to-end build


def v2_fixture(root: Path) -> dict:
    """Tiny v2 stores, a v2 docs cache containing RUBY_DUPLICATE and a v2 done list containing rubygems:oldgem."""
    meta = {}
    for kind, n in (("code", 300), ("general", 120)):
        d = root / "out" / f"{kind}-v2"
        d.mkdir(parents=True)
        array("H", [i % 8000 for i in range(n - 1)] + [v2.EOS]).tofile((d / "train.bin").open("wb"))
        array("H", [7, 8, v2.EOS]).tofile((d / "train.val.bin").open("wb"))
        shutil.copy(v2.TOKENIZER, d / "tokenizer.json")
        meta[kind] = {"tokens": n, "val_tokens": 3, "dtype": "uint16", "vocab_size": 8192, "bin": "train.bin", "val_bin": "train.val.bin",
                      "mix": {kind: 2}, "mix_fractions": {kind: 1.0}}
        (d / "train.meta.json").write_text(json.dumps(meta[kind]))
    docs = root / "cache" / "v2" / "docs"
    docs.mkdir(parents=True)
    h = hashlib.sha1(v2.NORM.sub(" ", RUBY_DUPLICATE.strip()).encode()).hexdigest()
    (docs / "code-train.jsonl").write_text(json.dumps({"h": h, "k": "code", "s": "rubygems:old", "p": "x.rb", "t": RUBY_DUPLICATE.strip()}) + "\n")
    (root / "cache" / "v2" / "done.jsonl").write_text(json.dumps({"task": "rubygems:oldgem", "status": "ok"}) + "\n")
    ev = root / "evals"
    ev.mkdir()
    (ev / "mbpp.jsonl").write_text(json.dumps({"text": "Write a function.", "test_list": [CONTAMINATED]}) + "\n")
    (ev / "humaneval.jsonl").write_text(json.dumps({"prompt": "def f():", "canonical_solution": "return 1"}) + "\n")
    (ev / "gsm8k.jsonl").write_text(json.dumps({"question": "1+1?", "answer": "2"}) + "\n")
    return meta | {"v2_hash": h}


def parquet_fixture(path: Path) -> Path | None:
    try:
        import pyarrow as pa
        import pyarrow.parquet as pq
    except ImportError:
        return None
    rows = [("Educational text number %d. " % i) * 40 for i in range(3)] + ["too short"]
    pq.write_table(pa.table({"text": rows}), path)
    return path


def u16(p: Path) -> array:
    a = array("H")
    a.frombytes(p.read_bytes())
    return a


@pytest.mark.skipif(not HAVE_FORGE, reason="needs target/release/forge and data/stores/base/tokenizer.json")
def test_end_to_end_build_with_root(tmp_path, monkeypatch):
    fx = v2_fixture(tmp_path)
    net = FakeNet(routes())
    monkeypatch.setattr(reg, "fetch", net)
    monkeypatch.setattr(reg, "reachable", lambda *a, **k: False)
    pk = tmp_path / "packages.txt"
    pk.write_text("maven:org.example:lib\nmaven:org.example:gpl-lib\nrubygems:fixgem\nrubygems:oldgem\nhackage:fixpkg\n")
    args = ["--root", str(tmp_path), "--packages", str(pk), "--evals", str(tmp_path / "evals"), "--max-disk-gb", "1"]
    pq = parquet_fixture(tmp_path / "fw.parquet")
    if pq:
        args += ["--parquet", str(pq)]
    assert v3.main(args) == 0

    out = tmp_path / "out"
    tok = v2.TOKENIZER.read_bytes()
    for name in v3.STORES:
        d = out / name
        assert {p.name for p in d.iterdir()} >= {"train.bin", "train.val.bin", "tokenizer.json", "train.meta.json", "manifest.json"}
        meta = json.loads((d / "train.meta.json").read_text())
        assert meta["dtype"] == "uint16" and meta["vocab_size"] == 8192 and (d / "tokenizer.json").read_bytes() == tok
        assert meta["tokens"] * 2 == (d / "train.bin").stat().st_size and meta["val_tokens"] * 2 == (d / "train.val.bin").stat().st_size
        man = json.loads((d / "manifest.json").read_text())
        assert man["sha256"]["train.bin"] == hashlib.sha256((d / "train.bin").read_bytes()).hexdigest()
        assert man["pipeline"].startswith("data/build_corpus_v3.py")
        assert max(u16(d / "train.bin")) < 8192
    code, gen, base = (json.loads((out / n / "manifest.json").read_text()) for n in v3.STORES)
    assert code["tokens"] == fx["code"]["tokens"] + code["new"]["tokens"] and code["new"]["tokens"] > 0
    assert gen["tokens"] == fx["general"]["tokens"] + gen["new"]["tokens"] and gen["new"]["tokens"] > 0
    assert (out / "code-v3" / "train.bin").read_bytes().startswith((out / "code-v2" / "train.bin").read_bytes())
    for f in ("train.bin", "train.val.bin"):
        assert (out / "base-v3" / f).read_bytes() == (out / "code-v3" / f).read_bytes() + (out / "general-v3" / f).read_bytes()
    assert u16(out / "code-v3" / "train.bin")[-1] == v2.EOS
    assert set(code["mix"]) == {"code-v2", "maven", "rubygems", "hackage"}
    assert {"general-v2", "maven", "rubygems", "hackage"} <= set(gen["mix"]) and (pq is None or "fineweb-edu" in gen["mix"])
    assert base["mix"] == {"code": sum(code["mix"].values()), "general": sum(gen["mix"].values())}

    man = tmp_path / "manifests"
    sources = {s["task"]: s for s in json.loads((man / "sources.json").read_text())}
    assert "rubygems:oldgem" not in sources and not any("oldgem" in u for u in net.calls)
    assert sources["maven:org.example:gpl-lib"]["status"] == "rejected-licence"
    for t in ("maven:org.example:lib", "rubygems:fixgem", "hackage:fixpkg"):
        s = sources[t]
        assert s["status"] == "ok" and reg.licence_ok(s["license"]) and s["attribution"] and len(s["sha256"]) == 64 and s["url"]
    assert sources["rubygems:fixgem"]["kept"] == 2 and sources["rubygems:fixgem"]["files"] == 3  # dup of v2 dropped
    assert sources["maven:org.example:lib"]["kept"] == 2 and sources["maven:org.example:lib"]["files"] == 4  # contaminated + generated dropped
    filters = json.loads((man / "filters.json").read_text())["filters"]
    assert filters["duplicate_v2"] == 1 and filters["contaminated"] == 1 and filters["generated"] == 1
    stores = json.loads((man / "stores.json").read_text())
    assert stores["evals_decontaminated_against"] == ["gsm8k", "humaneval", "mbpp"]
    assert stores["fineweb_edu"]["status"] == ("ok" if pq else "skipped: huggingface.co unreachable")
    assert stores["packages"]["maven"] == {"ok": 1, "rejected-licence": 1}

    index = (out / "base-v3" / "docs.sha1").read_bytes()
    digests = {index[i:i + 20].hex() for i in range(0, len(index), 20)}
    assert fx["v2_hash"] in digests and len(digests) == stores["dedup"]["v2_documents"] + stores["dedup"]["v3_documents"]
    cache = tmp_path / "cache" / "v3"
    assert not list((cache / "docs").glob("*.jsonl")) and (cache / "built.json").exists() and (cache / "done.jsonl").exists()
    assert not (out / ".v3-staging").exists()

    calls = len(net.calls)
    assert v3.main(args) == 0 and len(net.calls) == calls  # already built: nothing fetched again


@pytest.mark.skipif(not HAVE_FORGE, reason="needs target/release/forge and data/stores/base/tokenizer.json")
def test_fetch_only_then_resume_does_not_refetch(tmp_path, monkeypatch):
    v2_fixture(tmp_path)
    net = FakeNet(routes())
    monkeypatch.setattr(reg, "fetch", net)
    pk = tmp_path / "packages.txt"
    pk.write_text("hackage:fixpkg\nmaven:org.example:lib\n")
    args = ["--root", str(tmp_path), "--packages", str(pk), "--evals", str(tmp_path / "evals"), "--no-fineweb"]
    assert v3.main(args + ["--fetch-only"]) == 0
    docs = tmp_path / "cache" / "v3" / "docs"
    n_docs = sum(len(p.read_text().splitlines()) for p in docs.glob("*.jsonl"))
    with (docs / "code-train.jsonl").open("a") as f:
        f.write('{"h": "deadbeef')  # interrupted append
    calls = len(net.calls)
    assert v3.main(args) == 0 and len(net.calls) == calls
    stores = json.loads((tmp_path / "manifests" / "stores.json").read_text())
    assert stores["dedup"]["v3_documents"] == n_docs
    done = [json.loads(x)["task"] for x in (tmp_path / "cache" / "v3" / "done.jsonl").read_text().splitlines()]
    assert sorted(done) == ["hackage:fixpkg", "maven:org.example:lib"]


def test_disk_guard_refuses_before_fetching(tmp_path, monkeypatch):
    if not HAVE_FORGE:
        pytest.skip("needs forge")
    v2_fixture(tmp_path)
    net = FakeNet(routes())
    monkeypatch.setattr(reg, "fetch", net)
    pk = tmp_path / "packages.txt"
    pk.write_text("hackage:fixpkg\n")
    assert v3.main(["--root", str(tmp_path), "--packages", str(pk), "--evals", str(tmp_path / "evals"), "--max-disk-gb", "1e-9"]) == 3
    assert net.calls == [] and not (tmp_path / "out" / "code-v3").exists()
    guard = v3.Disk(tmp_path / "cache", tmp_path / "out", 1000, 1e-5)
    assert guard.over(0) is None and "max-disk-gb" in guard.over(1e5)
